[package]
name = "openai-api-rs"
version = "2.1.1"
edition = "2021"
authors = ["Dongri Jin <dongrify@gmail.com>"]
license = "MIT"
description = "OpenAI API client library for Rust (unofficial)"
repository = "https://github.com/dongri/openai-api-rs"

[dependencies]
dotenv = "0.15.0"
toml = "0.8.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1"
features = ["derive"]
default-features = false

[dependencies.serde_json]
version = "1"
default-features = false

[dependencies.minreq]
version = "2"
default-features = false
features = ["https-rustls", "json-using-serde"]
